### ISSUE TITLE
Illegal State Exception

### ISSUE THREAD

**Issue by duckchip** [EmicoEcommerce/Magento2Tweakwise-archived#21]
Hey guys,

We are having an error on product category pages when installing the Tweakwise module 

Environment
--
* PHP Version: 7.0
* Magento Version: 2.2.1 Enterprise
* Tweakwise Version: v1.0.7
* Tweakwise Export Version: v1.0.10
* Magento Deploy Mode: Production
* Third party modules: 

Steps to reproduce
--
1. Install Tweakwise on develop
2. Deploy to production on Magento Cloud 

Actual result
--
1. The Product pages (category) are returning a 503 error.
```
{"0":"Illegal state","1":"
#0 \/app\/vendor\/emico\/tweakwise\/src\/Block\/Catalog\/Product\/ProductList\/Featured.php(86): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->addFieldToFilter('entity_id', Array)\n
#1 \/app\/vendor\/magento\/module-catalog\/Block\/Product\/ListProduct.php(268): Emico\\Tweakwise\\Block\\Catalog\\Product\\ProductList\\Featured->_getProductCollection()\n
#2 \/app\/vendor\/magento\/module-page-cache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n
#3 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\\n<script>\\n    t...')\n
#4 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n
#5 \/app\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(52): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n
#6 \/app\/vendor\/magento\/framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n
#7 \/app\/vendor\/magento\/framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#8 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#9 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n
#10 \/app\/vendor\/gene\/bluefoot\/Plugin\/RenderPageBuilder.php(66): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#11 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(135): Gene\\BlueFoot\\Plugin\\RenderPageBuilder->aroundRenderResult(Object(Magento\\Framework\\View\\Result\\Page\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#12 \/app\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#13 \/app\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(26): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, NULL)\n
#14 \/app\/vendor\/magento\/framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n
#15 \/app\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n
#16 \/app\/pub\/index.php(37):
```

Thx in advance

Kind regards

Tristan

**Comment by duckchip** [comment]
Hey guys, 

Any news on this issue? It's quite important for us to have the module up and running.

I also see that this issue has been referenced, so there are others with the same problem. 

kind regards

Tristan

**Comment by Fgruntjes** [comment]
We researched the issue and fixed it. It was due to an unexpected method call on one of the layout blocks while the module is disabled.
